POST {{host}}/tournament/
Authorization: Basic {{token}}
Content-Type: application/json

{
}

// response
//{
//  "id": "UUID-UUID",
//  "name": "name",
//  "date": "2023-08-30",
//}


GET /user/{username OR userId}
return MemberDto