name: Deploy - Dev

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/chessgrinder/dev-docker
            docker pull vshefer/chessgrinder:latest
            docker compose down
            docker compose up -d
