name: Build and Push Release Docker Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: vshefer/chessgrinder:latest
