name: DockerHub Publish

on:
  workflow_call:
    inputs:
      tags:
        description: 'Full Docker image references, newline-separated (e.g. "vshefer/chessgrinder:dev" or "vshefer/chessgrinder:v1.2.3\nvshefer/chessgrinder:latest")'
        default: 'vshefer/chessgrinder:dev'
        required: false
        type: string
      version:
        description: "A version of the Application"
        default: 'dev'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ${{ inputs.tags }}
          build-args: |
            VERSION=${{ inputs.version }}
