name: DockerHub Publish

on:
  workflow_call:
    inputs:
      tags:
        description: 'Docker Image Tags (newline-separated, e.g. "dev" or "v1.2.3\nlatest")'
        default: 'dev'
        required: false
        type: string
      version:
        description: "A version of the Application"
        default: 'dev'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build tags list
        id: tags
        run: |
          {
            echo 'list<<EOF'
            echo "${{ inputs.tags }}" | sed 's/^/vshefer\/chessgrinder:/'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ${{ steps.tags.outputs.list }}
          build-args: |
            VERSION=${{ inputs.version }}
